name: Gem Tests

on: 
  pull_request:
  push:
    branches:
      - master

jobs:
  run:
    name: Run Tests for Ruby ${{ matrix.ruby }}

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pg_ltree_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 'head'
          - '3.4'
          - '3.3'
          - '3.2'
          - '3.1'
          - '3.0'
          - '2.7'

    continue-on-error: ${{ matrix.ruby == 'head' }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Setup DB
        run: cp spec/database.yml.sample spec/database.yml
      
      - name: Install dependencies
        run: bundle exec appraisal install

      - name: Run tests
        run: bundle exec appraisal rake spec
